import * as vscode from 'vscode';

export class ContextExporter {
    public async exportContext(): Promise<void> {
        const options: vscode.QuickPickItem[] = [
            {
                label: '$(clipboard) Copy to Clipboard',
                description: 'Copy context summary to clipboard'
            },
            {
                label: '$(file) Save to File',
                description: 'Save context summary to a markdown file'
            },
            {
                label: '$(new-file) Create Handoff Document',
                description: 'Create a new document with handoff template'
            }
        ];

        const selection = await vscode.window.showQuickPick(options, {
            placeHolder: 'How would you like to export the context?'
        });

        if (!selection) {
            return;
        }

        const context = this.generateContextSummary();

        if (selection.label.includes('Clipboard')) {
            await vscode.env.clipboard.writeText(context);
            vscode.window.showInformationMessage('Context summary copied to clipboard');
        } else if (selection.label.includes('Save to File')) {
            await this.saveToFile(context);
        } else if (selection.label.includes('Create Handoff')) {
            await this.createHandoffDocument(context);
        }
    }

    private generateContextSummary(): string {
        const now = new Date();
        const workspace = vscode.workspace.workspaceFolders?.[0];
        const workspaceName = workspace ? workspace.name : 'Unknown';
        const activeEditor = vscode.window.activeTextEditor;
        const currentFile = activeEditor ? activeEditor.document.fileName : 'None';

        let summary = `# Copilot Session Handoff Summary\n\n`;
        summary += `**Generated:** ${now.toLocaleString()}\n`;
        summary += `**Workspace:** ${workspaceName}\n`;
        summary += `**Current File:** ${currentFile}\n\n`;
        
        summary += `## Session Context\n\n`;
        summary += `### Current Working State\n`;
        
        if (activeEditor) {
            const selection = activeEditor.selection;
            if (!selection.isEmpty) {
                summary += `- Active selection in ${activeEditor.document.fileName}\n`;
                summary += `- Lines: ${selection.start.line + 1} - ${selection.end.line + 1}\n`;
            }
            summary += `- Language: ${activeEditor.document.languageId}\n`;
        }

        summary += `\n### Open Editors\n`;
        const openEditors = vscode.window.visibleTextEditors;
        openEditors.forEach(editor => {
            summary += `- ${editor.document.fileName}\n`;
        });

        summary += `\n### Recent Terminal Commands\n`;
        summary += `*(Note: Manually add recent commands you've executed)*\n\n`;

        summary += `## Tasks and Context for Next Session\n\n`;
        summary += `### What I Was Working On\n`;
        summary += `*(Describe the current task or problem)*\n\n`;
        
        summary += `### Key Decisions Made\n`;
        summary += `*(List important decisions or approaches taken)*\n\n`;
        
        summary += `### Next Steps\n`;
        summary += `*(What should be done next)*\n\n`;
        
        summary += `### Important Context\n`;
        summary += `*(Any other relevant information)*\n\n`;

        summary += `---\n`;
        summary += `*Generated by Copilot Handoff extension*\n`;

        return summary;
    }

    private async saveToFile(content: string) {
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-').split('T')[0];
        const defaultUri = vscode.Uri.file(`copilot-handoff-${timestamp}.md`);

        const uri = await vscode.window.showSaveDialog({
            defaultUri,
            filters: {
                'Markdown': ['md'],
                'Text': ['txt']
            }
        });

        if (uri) {
            await vscode.workspace.fs.writeFile(uri, Buffer.from(content, 'utf8'));
            vscode.window.showInformationMessage(`Context saved to ${uri.fsPath}`);
            
            // Optionally open the file
            const openFile = await vscode.window.showInformationMessage(
                'Open the saved file?',
                'Yes',
                'No'
            );
            
            if (openFile === 'Yes') {
                const doc = await vscode.workspace.openTextDocument(uri);
                await vscode.window.showTextDocument(doc);
            }
        }
    }

    private async createHandoffDocument(context: string) {
        const doc = await vscode.workspace.openTextDocument({
            content: context,
            language: 'markdown'
        });
        
        await vscode.window.showTextDocument(doc);
        vscode.window.showInformationMessage('Handoff document created. Fill in the template sections.');
    }
}
